// Dark product theme tokens. Keep these values in the Vite theme entrypoint so
// runtime Ant Design tokens and legacy Less variables share one source.
export default {
  colorPrimary: '#2F80FF',
  colorLink: '#52A0FF',
  colorInfo: '#2F80FF',
  colorSuccess: '#35D07F',
  colorWarning: '#FFB454',
  colorError: '#FF6474',
  colorBgBase: '#0A1422',
  colorBgLayout: '#0A1422',
  colorBgContainer: '#102238',
  colorBgElevated: '#172F49',
  colorFillAlter: '#172F49',
  colorFillSecondary: '#1D3A59',
  colorBorder: '#35516F',
  colorBorderSecondary: '#35516F',
  colorTextBase: '#F4F7FC',
  colorText: '#F4F7FC',
  colorTextSecondary: '#C4D0DE',
  colorTextTertiary: '#96A9BD',
  colorTextQuaternary: '#8799AD',
  borderRadius: 8,
  fontSize: 14,
  lineHeight: 1.5714,
  fontFamily: '"Segoe UI", "Microsoft YaHei", "PingFang SC", "Hiragino Sans GB", "Noto Sans SC", AliRegular, sans-serif',
  fontWeightStrong: 600,
  fontSizeHeading1: 28,
  fontSizeHeading2: 24,
  fontSizeHeading3: 20,
  fontSizeHeading4: 18,
  fontSizeHeading5: 16,
}
